- name: Create user ansible Ubuntu/Debian.
  hosts: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    users:
      - "ansible"
      - "teste"
  tasks:
    - name: "Create user accounts"
      user:
        name: "{{ item }}"
        groups: "sudo"
      with_items: "{{ users }}"
    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa_'+ item + '.pub') }}"
      with_items: "{{ users }}"
    - name: "Allow admin users to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers"
        state: "present"
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL) NOPASSWD: ALL"

- name: Create user ansible RHEL/CentOS.
  hosts: centos
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    users:
      - "ansible"
      - "teste"
  tasks:
    - name: "Create user accounts"
      user:
        name: "{{ item }}"
        groups: "wheel"
      with_items: "{{ users }}"
    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa_'+ item + '.pub') }}"
      with_items: "{{ users }}"
    - name: "Allow admin users to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers"
        state: "present"
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
