- name: Install Nginx Ubuntu/Debian
  hosts: nginx
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Install Nginx Ubuntu/Debian.
    apt:
      name: nginx
      state: latest
    when: inventory_hostname in groups["ubuntu"]
    notify:
      - startservice
  handlers:
  - name: startservice
    service:
      name: nginx
      state: restarted
      enabled: yes

#############################

- name: Install Nginx RHEL/CentOS
  hosts: nginx
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Install nginx RHEL/CentOS.
    yum:
      name: nginx
      state: latest
    when: inventory_hostname in groups["centos"]
    notify:
    - startservice
  handlers:
  - name: startservice
    service:
      name: nginx
      state: restarted
      enabled: yes
